### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by rahulsom** [hzbarcea/x12-parser#1]
Great lib. Thanks for writing it. Do you think you would be able to set up a sync with maven central?
That way users can use it in their project without having to build it.

**Comment by hzbarcea** [comment]
@rahulsom , to do so it would require a bit more changes. There wasn't a lot of interest in it so I didn't have to spend the time. If you are interested and have a timeline, please let me know to make the necessary modifications and publish it in maven central.

**Comment by cstenkes** [comment]
we also  will be happy if it would be in the Maven Central Repository. We use this library for a logistic portal project.

**Comment by rahulsom** [comment]
@cstenkes I've had luck with https://jitpack.io/#hzbarcea/x12-parser/x12-1.0 as a way to achieve similar results.

**Comment by hzbarcea** [comment]
I didn't know there is more interest in this. Yes, I can do that, not problem. It requires a bit of cleanup, but I can spend a bit of time for that.

I can ever maintain it more actively if it's not time wasted.

**Comment by cstenkes** [comment]
It would be great! Thanks in advance.

**Comment by cstenkes** [comment]
When will it be available in the maven central repo?

**Comment by hzbarcea** [comment]
I am involved in a project that uses EDI messages and we were looking at some improvements. We are looking into the best way of doing it to try to create a community and grow the code that was stagnant for a long time. It is not at the top of my agenda, but since you poked me by asking, I'll make it a higher priority. I'll get back with a concrete date next week.

**Comment by cstenkes** [comment]
@hzbarcea Do you know when will this lib avaliable at Central Maven repo?We don't allow to use sources from another reporsitory :(

**Comment by hzbarcea** [comment]
I wanted to close this one for a long time and I am finally able to.

This repository moved to [apifocal/x12-parser](https://github.com/apifocal/x12-parser) and is now published in [Maven Central](http://central.maven.org/maven2/org/apifocal/health/x12/1.1/). Please note the the artifact coordinates changed to: `org.apifocal.health:x12:1.1` so your dependency should look as below.

Other news is that apifocal made a commitment to support this library, so any issues/comments you might have, contributions, etc. should be reported there.

```
<dependency>
  <groupId>org.apifocal.health</groupId>
  <artifactId>x12</artifactId>
  <version>1.1</version>
</dependency>
```

Happy Holidays!

**Comment by cstenkes** [comment]
Hi Hadrian, Thanks for your effort! In the new year we will build in the new version to our project. Csaba

**Comment by cstenkes** [comment]
Hi Hadrian,

I tried the binary version of X12 parser from Central Maven Repo, but the build was not successful at our environment. Our project is a little bit old and we use still Java 7. Unfortunately we can't use Java 8 or more class file format and we can't do java upgrade at the moment  :(

It is possible the library to be complied by Java 7 as the target platform and distributed to the Central Repo again?

BR, Csaba

**Comment by hzbarcea** [comment]
Hi Csaba,

I think you should lobby for moving to Java 8. There are many reasons for that, including the fact that Java 7 is past end of life for years now.

Also, please open future issues/requests with the apifocal project. Apifocal is not using Java 7 anymore and I doubt your request is enough to warrant deploying test automation and the support infrastructure for Java 7.

Cheers,
Hadrian
