### ISSUE TITLE
X12 850 EDI java parser

### ISSUE THREAD

**Issue by tayaltayal** [hzbarcea/x12-parser#2]
Hi,

I am looking for a java parser to parse X12 850 EDI file. I was going through your parser and it seems that it is only for 835 format. Please let me know if we have 850 parser available or it can be configured?

**Comment by srinivasch29** [comment]
Hi,
 I am also looking for the the parser to parse EDI 850 file, It would be appreciated if you provide some information on it.

**Comment by Lucier82** [comment]
This parser will suite your needs but you need to define the parsing object. My team has been using EDI Technical Reports (TR3) to define the Cf object which can be of any X12 type including your 850. The 835 in the documentation is merely an example. The Cf drives the ability to parse an X12 file of some defined type. Currently my team has build these for 837I, P & D as well as 835, 999, 277CA, 277, 834 and 820. If you can get your hands on the TR3 the rest of the process should fall into place.

**Comment by hzbarcea** [comment]
@Lucier82 's answer is correct, I assume this can be closed.
